### ISSUE TITLE
Too much goroutine 

### ISSUE THREAD

**Issue by darkrain** [eduhenke/go-ocpp#13]
Hello! Some times i get this erros on the cs

    goroutine 68858 [chan send, 1930 minutes]:
    github.com/voltbras/go-ocpp/ws.(*Conn).ReadMessageAsync.func1(0xc00248b3e0, 0xc00080a640)
	    /go/pkg/mod/github.com/voltbras/go-ocpp@v1.1.0/ws/conn.go:170 +0x57
    created by github.com/voltbras/go-ocpp/ws.(*Conn).ReadMessageAsync
	    /go/pkg/mod/github.com/voltbras/go-ocpp@v1.1.0/ws/conn.go:169 +0x65
    
    goroutine 68884 [chan send, 1930 minutes]:
    github.com/voltbras/go-ocpp/ws.(*Conn).ReadMessageAsync.func1(0xc00256a9c0, 0xc00042f500)
	    /go/pkg/mod/github.com/voltbras/go-ocpp@v1.1.0/ws/conn.go:170 +0x57
    created by github.com/voltbras/go-ocpp/ws.(*Conn).ReadMessageAsync
	    /go/pkg/mod/github.com/voltbras/go-ocpp@v1.1.0/ws/conn.go:169 +0x65
    
    goroutine 68921 [chan send, 1930 minutes]:
    github.com/voltbras/go-ocpp/ws.(*Conn).ReadMessageAsync.func1(0xc0025339e0, 0xc00080b500)
	    /go/pkg/mod/github.com/voltbras/go-ocpp@v1.1.0/ws/conn.go:170 +0x57
    created by github.com/voltbras/go-ocpp/ws.(*Conn).ReadMessageAsync
    ^C	/go/pkg/mod/github.com/voltbras/go-ocpp@v1.1.0/ws/conn.go:169 +0x65

Have any idea?

**Comment by Gaadin** [comment]
Hi @darkrain,
I am getting same issue as mentioned above , do let me know if you are able to resolve it, apart from this issue started getting fatal error
fatal error: concurrent map writes
fatal error: concurrent map writes 

Let me know if you have any idea about these issues.
